#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f counter.vcd

#run Verilator to translate Verilog into C++ including the testbench
verilator -Wall --cc --trace counter.sv --exe counter_tb.cpp

#build C++ project through 'make' automatically generated by Verilator
make -j -C obj_dir/ -f Vcounter.mk Vcounter

# run the executable file
obj_dir/Vcounter